Clean result message code in test-js-with-node.
Remove duplicate code after quick fix in passing returned code.

Fixes: 1489.

diff --git a/tools/test-js-with-node b/tools/test-js-with-node
--- a/tools/test-js-with-node
+++ b/tools/test-js-with-node
@@ -1,15 +1,17 @@
 #!/usr/bin/env bash
-set -e
 
 cd "$(dirname "$0")"/..
 
 export NODE_PATH=/usr/lib/nodejs:static
+export PATH=$PATH:node_modules/.bin
 
 INDEX_JS=frontend_tests/zjsunit/index.js
 NODEJS=$(which nodejs || which node)
+
 if [ "$1" = "cover" ]; then
   # Run a coverage test with Istanbul.
-  istanbul cover "$INDEX_JS" && echo "Test(s) passed. SUCCESS!" || echo "FAIL - Test(s) failed"
+  istanbul cover "$INDEX_JS";
+  ret=$?;
 
 elif [ "$1" = "-h" -o "$1" = "--help" ]; then
   echo "Usage:
@@ -23,5 +25,14 @@ elif [ "$1" = "-h" -o "$1" = "--help" ]; then
 else
   # Normal testing, no coverage analysis.
   # Run the index.js test runner, which runs all the other tests.
-  "$NODEJS" --stack-trace-limit=100 "$INDEX_JS" $@ && echo "Test(s) passed. SUCCESS!" || echo "FAIL - Test(s) failed"
+  "$NODEJS" --stack-trace-limit=100 "$INDEX_JS" $@;
+  ret=$?;
 fi
+
+if [ $ret = '0' ]; then
+    echo "Test(s) passed. SUCCESS!"
+else
+    echo "FAIL - Test(s) failed"
+fi
+
+exit $ret
